;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Attribute.Base.Defense",DevComment="")
GameplayTagList=(Tag="Attribute.Base.Food",DevComment="Current food value.")
GameplayTagList=(Tag="Attribute.Base.Health",DevComment="Current health value.")
GameplayTagList=(Tag="Attribute.Base.MaxFood",DevComment="Maximum food value.")
GameplayTagList=(Tag="Attribute.Base.MaxHealth",DevComment="Maximum health value.")
GameplayTagList=(Tag="Attribute.Base.MaxOxygen",DevComment="Maximum oxygen level.")
GameplayTagList=(Tag="Attribute.Base.MaxStamina",DevComment="Maximum stamina value.")
GameplayTagList=(Tag="Attribute.Base.MaxWater",DevComment="Maximum water value.")
GameplayTagList=(Tag="Attribute.Base.MaxWeight",DevComment="")
GameplayTagList=(Tag="Attribute.Base.Oxygen",DevComment="Current oxygen level.")
GameplayTagList=(Tag="Attribute.Base.Stamina",DevComment="Current stamina value.")
GameplayTagList=(Tag="Attribute.Base.Water",DevComment="Current water value.")
GameplayTagList=(Tag="Attribute.Base.Weight",DevComment="")
GameplayTagList=(Tag="Attribute.Derived.TestTag",DevComment="")
GameplayTagList=(Tag="Attribute.Status.Food.Empty",DevComment="Food is empty.")
GameplayTagList=(Tag="Attribute.Status.Food.Full",DevComment="Food is full.")
GameplayTagList=(Tag="Attribute.Status.Food.Hungry",DevComment="Food is low.")
GameplayTagList=(Tag="Attribute.Status.Food.Starving",DevComment="Food is critically low.")
GameplayTagList=(Tag="Attribute.Status.Health.Critical",DevComment="Health is critically low.")
GameplayTagList=(Tag="Attribute.Status.Health.Full",DevComment="Health is full.")
GameplayTagList=(Tag="Attribute.Status.Health.Low",DevComment="Health is low.")
GameplayTagList=(Tag="Attribute.Status.Stamina.Empty",DevComment="Stamina is empty.")
GameplayTagList=(Tag="Attribute.Status.Stamina.Full",DevComment="Stamina is full.")
GameplayTagList=(Tag="Attribute.Status.Stamina.Low",DevComment="Stamina is low.")
GameplayTagList=(Tag="Attribute.Status.Water.Dehydrated",DevComment="Water is critically low.")
GameplayTagList=(Tag="Attribute.Status.Water.Empty",DevComment="Water is empty.")
GameplayTagList=(Tag="Attribute.Status.Water.Full",DevComment="Water is full.")
GameplayTagList=(Tag="Attribute.Status.Water.Thirsty",DevComment="Water is low.")
GameplayTagList=(Tag="Attribute.Status.Weight.Encumbered",DevComment="")
GameplayTagList=(Tag="Attribute.Status.Weight.Overburdened",DevComment="")
GameplayTagList=(Tag="State.Dead",DevComment="")

