;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Attribute.Base.Defense",DevComment="")
GameplayTagList=(Tag="Attribute.Base.Food",DevComment="Current food value.")
GameplayTagList=(Tag="Attribute.Base.Health",DevComment="Current health value.")
GameplayTagList=(Tag="Attribute.Base.MaxFood",DevComment="Maximum food value.")
GameplayTagList=(Tag="Attribute.Base.MaxHealth",DevComment="Maximum health value.")
GameplayTagList=(Tag="Attribute.Base.MaxOxygen",DevComment="Maximum oxygen level.")
GameplayTagList=(Tag="Attribute.Base.MaxStamina",DevComment="Maximum stamina value.")
GameplayTagList=(Tag="Attribute.Base.MaxWater",DevComment="Maximum water value.")
GameplayTagList=(Tag="Attribute.Base.MaxWeight",DevComment="")
GameplayTagList=(Tag="Attribute.Base.Oxygen",DevComment="Current oxygen level.")
GameplayTagList=(Tag="Attribute.Base.Stamina",DevComment="Current stamina value.")
GameplayTagList=(Tag="Attribute.Base.StaminaRecoveryPerMinute",DevComment="")
GameplayTagList=(Tag="Attribute.Base.Water",DevComment="Current water value.")
GameplayTagList=(Tag="Attribute.Base.Weight",DevComment="")
GameplayTagList=(Tag="Attribute.Derived.FoodDrainPerHour",DevComment="Food drain per hour.")
GameplayTagList=(Tag="Attribute.Derived.StaminaDrainSprintPerMinute",DevComment="Stamina sprint drain per minute")
GameplayTagList=(Tag="Attribute.Derived.WaterDrainPerHour",DevComment="Water drain per hour.")
GameplayTagList=(Tag="Attribute.Status.Food.Empty",DevComment="Food is empty.")
GameplayTagList=(Tag="Attribute.Status.Food.Full",DevComment="Food is full.")
GameplayTagList=(Tag="Attribute.Status.Food.Hungry",DevComment="Food is low.")
GameplayTagList=(Tag="Attribute.Status.Food.Starving",DevComment="Food is critically low.")
GameplayTagList=(Tag="Attribute.Status.Health.Critical",DevComment="Health is critically low.")
GameplayTagList=(Tag="Attribute.Status.Health.Full",DevComment="Health is full.")
GameplayTagList=(Tag="Attribute.Status.Health.Low",DevComment="Health is low.")
GameplayTagList=(Tag="Attribute.Status.Stamina.Empty",DevComment="Stamina is empty.")
GameplayTagList=(Tag="Attribute.Status.Stamina.Full",DevComment="Stamina is full.")
GameplayTagList=(Tag="Attribute.Status.Stamina.Low",DevComment="Stamina is low.")
GameplayTagList=(Tag="Attribute.Status.Water.Dehydrated",DevComment="Water is critically low.")
GameplayTagList=(Tag="Attribute.Status.Water.Empty",DevComment="Water is empty.")
GameplayTagList=(Tag="Attribute.Status.Water.Full",DevComment="Water is full.")
GameplayTagList=(Tag="Attribute.Status.Water.Thirsty",DevComment="Water is low.")
GameplayTagList=(Tag="Attribute.Status.Weight.Encumbered",DevComment="")
GameplayTagList=(Tag="Attribute.Status.Weight.Overburdened",DevComment="")
GameplayTagList=(Tag="AttributeEffect.Block.All",DevComment="Blocks all attribute effects.")
GameplayTagList=(Tag="AttributeEffect.Block.Drain",DevComment="Blocks all drain effects.")
GameplayTagList=(Tag="AttributeEffect.Block.Drain.Food",DevComment="Blocks food drain.")
GameplayTagList=(Tag="AttributeEffect.Block.Drain.Health",DevComment="Blocks health drain.")
GameplayTagList=(Tag="AttributeEffect.Block.Drain.Oxygen",DevComment="Blocks oxygen drain.")
GameplayTagList=(Tag="AttributeEffect.Block.Drain.Stamina",DevComment="Blocks stamina drain.")
GameplayTagList=(Tag="AttributeEffect.Block.Drain.Water",DevComment="Blocks water drain.")
GameplayTagList=(Tag="AttributeEffect.Block.Regen",DevComment="Blocks all regeneration.")
GameplayTagList=(Tag="AttributeEffect.Block.Regen.Food",DevComment="Blocks food regeneration.")
GameplayTagList=(Tag="AttributeEffect.Block.Regen.Health",DevComment="Blocks health regeneration.")
GameplayTagList=(Tag="AttributeEffect.Block.Regen.Stamina",DevComment="Blocks stamina regeneration.")
GameplayTagList=(Tag="AttributeEffect.Block.Regen.Water",DevComment="Blocks water regeneration.")
GameplayTagList=(Tag="AttributeEffect.Drain.Food",DevComment="Applies food drain.")
GameplayTagList=(Tag="AttributeEffect.Drain.Oxygen",DevComment="Applies oxygen drain.")
GameplayTagList=(Tag="AttributeEffect.Drain.Stamina",DevComment="Applies stamina drain.")
GameplayTagList=(Tag="AttributeEffect.Drain.Water",DevComment="Applies water drain.")
GameplayTagList=(Tag="AttributeEffect.Regen.Food",DevComment="Applies food regeneration.")
GameplayTagList=(Tag="AttributeEffect.Regen.Health",DevComment="Applies health regeneration.")
GameplayTagList=(Tag="AttributeEffect.Regen.Stamina",DevComment="Applies stamina regeneration.")
GameplayTagList=(Tag="AttributeEffect.Regen.Water",DevComment="Applies water regeneration.")

