;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Crafting.Station.AdvanceWorkbench",DevComment="")
+GameplayTagList=(Tag="Crafting.Station.Campfire",DevComment="")
+GameplayTagList=(Tag="Crafting.Station.CookingStation",DevComment="")
+GameplayTagList=(Tag="Crafting.Station.Forge",DevComment="")
+GameplayTagList=(Tag="Crafting.Station.PlayerInventory",DevComment="")
+GameplayTagList=(Tag="Crafting.Station.Smelter",DevComment="")
+GameplayTagList=(Tag="Crafting.Station.Workbench",DevComment="")
+GameplayTagList=(Tag="Interaction.Type.Pickup",DevComment="")

